CREATE TABLE IF NOT EXISTS Artistas (
	Id INTEGER  PRIMARY KEY AUTOINCREMENT,
	Email TEXT UNIQUE NOT NULL,
	'Fecha Nacimiento' TEXT,
	Nombre TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Albums (
	Id INTEGER  PRIMARY KEY AUTOINCREMENT,
	Titulo TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Canciones (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Nombre TEXT ,
	ArtistaId INTEGER REFERENCES Artistas
);

CREATE TABLE IF NOT EXISTS 'Albums-Canciones' (
	IdAlbum INTEGER REFERENCES Albums,
	IdCancion INTEGER REFERENCES Canciones
);
