CREATE TABLE Departamentos (
	Id INTEGER UNIQUE NOT NULL PRIMARY KEY,
	Nombre TEXT NOT NULL,
	Lugar TEXT
);

CREATE TABLE Empleados (
	ID INTEGER UNIQUE NOT NULL PRIMARY KEY,
	Nombre TEXT NOT NULL,
	Jefe INTEGER REFERENCES Empleados,
	Salario INTEGER,
	Bonus INTEGER,
	Puesto TEXT,
	DepId INTEGER REFERENCES Departamentos
);
